title: Reece Herbert | Robotics & AI

description: >-
  Robotics, ROS2, embedded systems, simulation,
  IoT, university coursework, and personal projects.

theme: minima

plugins:
  - jekyll-feed

collections:
  society-projects:
    output: true
    permalink: /society-projects/:name/

  course-projects:
    output: true
    permalink: /course-projects/:name/

  personal-projects:
    output: true
    permalink: /personal-projects/:name/

  university:
    output: true
    permalink: /university/:name/
